version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./volumes/nginx/:/shared/
      - ./volumes/nginx/logs/:/etc/nginx/logs/
      # - ./volumes/nginx:/etc/nginx/conf.d/mysite.template
    command: nginx -c /shared/nginx.conf -g "daemon off;"
    depends_on:
      - db
      - reservation
      - authentication
      - usersdb    
      - rabbitmq
  db:
    privileged: true
    image: mariadb
    labels:
      - "app=db"
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - ./volumes/db/data:/var/lib/mysql
      - ./volumes/db/conf:/etc/mysql/conf.d
      - ./volumes/db/certs:/etc/mysql/ssl
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=reservation     
      - MYSQL_ROOT_HOST=%
  reservation:
    build:
      context: ./reservation/
    labels:
      - "app=reservation"
    restart: always
    volumes:
      - ./reservation/:/reservation/
    environment:
      - PORT=3000
      - DEBUG=reservation:*
    depends_on:
      - db
      - rabbitmq
      - authentication
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  authentication:
    build: 
      context: ./authentication/
    labels:
      - "app=authentication"
    restart: always
    volumes:
      - ./authentication/:/authentication/
    environment:
      - PORT=3001
      - DEBUG=authentication:*
    depends_on:
      - usersdb
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
   
  usersdb:
    privileged: true
    image: mariadb
    labels:
      - "app=usersdb"
    restart: always
    ports:
      - "3312:3306"
    volumes:
      - ./volumes/usersdb/data:/var/lib/mysql
      - ./volumes/usersdb/conf:/etc/mysql/conf.d
      - ./volumes/usersdb/certs:/etc/mysql/ssl
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_HOST=%
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.6.0-management
    # volumes:
    #   - /volumes/rabbit1:/var/lib/rabbitmq
    #   - /volumes/conf/:/etc/rabbitmq/
    labels:
      - "app=rabbitmq"
    environment:
    - HOSTNAME=rabbitmq
    - RABBITMQ_NODENAME=rabbitmq
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password

  


  